# This file was generated by GoReleaser. DO NOT EDIT.
cask "database-connection-manager" do
  name "database-connection-manager"
  desc ""
  homepage ""
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbcm"

  on_macos do
    on_intel do
      url "https://github.com/pasca-l/database-connection-manager/releases/download/v#{version}/database-connection-manager_Darwin_x86_64.tar.gz"
      sha256 "881b18343453b71d086d58cb4eaff44dbfd552996da11f6e2e6244e389d5fcd8"
    end
    on_arm do
      url "https://github.com/pasca-l/database-connection-manager/releases/download/v#{version}/database-connection-manager_Darwin_arm64.tar.gz"
      sha256 "f6d95e9b49694d54df99c9b29aeff385709a83f71d30e13a324e5ed7ac95b0f7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pasca-l/database-connection-manager/releases/download/v#{version}/database-connection-manager_Linux_x86_64.tar.gz"
      sha256 "85b4d214a57a464a9592466bc5d78f2fa4b8cd5503362888ba9a7dea01dc5558"
    end
    on_arm do
      url "https://github.com/pasca-l/database-connection-manager/releases/download/v#{version}/database-connection-manager_Linux_arm64.tar.gz"
      sha256 "df825fcea79fd3fbcd0c70ddcaa11d2c2f678732a87b1311f5693d7c4c84cb44"
    end
  end

  # No zap stanza required
end
