# This file was generated by GoReleaser. DO NOT EDIT.
cask "database-connection-manager" do
  name "database-connection-manager"
  desc ""
  homepage ""
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "database-connection-manager"

  on_macos do
    on_intel do
      url "https://github.com/pasca-l/database-connection-manager/releases/download/v#{version}/database-connection-manager_Darwin_x86_64.tar.gz"
      sha256 "faa4a4f13f5cc0935eecfd5b97f15c14712e93034c0aa0b7f823584bb303cd6d"
    end
    on_arm do
      url "https://github.com/pasca-l/database-connection-manager/releases/download/v#{version}/database-connection-manager_Darwin_arm64.tar.gz"
      sha256 "1c42e9d1b92abd1cf827fdd71213e3f87e654d23456b601b032827225922051b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pasca-l/database-connection-manager/releases/download/v#{version}/database-connection-manager_Linux_x86_64.tar.gz"
      sha256 "9a3a6678b071550f06cf137c2e9de2ecb54162161a2f8e6b1f8a3c94451423d4"
    end
    on_arm do
      url "https://github.com/pasca-l/database-connection-manager/releases/download/v#{version}/database-connection-manager_Linux_arm64.tar.gz"
      sha256 "116bdcbe4d7cb549a2625c01ddb86a7fbcb29bb7eec275c1f0ca085d9aa54753"
    end
  end

  # No zap stanza required
end
